services:
  app:
    build: .
    image: polytech:latest
    container_name: polytech-app
    environment:
      SPRING_PROFILES_ACTIVE: "postgres"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    restart: unless-stopped

  cache:
    image: redis:7-alpine
    container_name: polytech-cache
    ports:
      - "6379:6379"
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: polytech-db
    environment:
      POSTGRES_DB: polytech
      POSTGRES_USER: polytech
      POSTGRES_PASSWORD: polytech
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  pgdata: {}
