services:
  app:
    build: .
    image: polytech:latest
    container_name: polytech-app
    environment:
      SPRING_PROFILES_ACTIVE: "postgres"
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: polytech-db
    environment:
      POSTGRES_DB: polytech
      POSTGRES_USER: polytech
      POSTGRES_PASSWORD: polytech
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
